### PR TITLE
util attribute malloc additions.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by robertswiecki** [comment]
Hi,

I'm ok with this change, though reading through https://stackoverflow.com/questions/18485447/gcc-attribute-malloc it seems that it should be applied to memory in an undefined yet state?

So, probably with _Malloc and with _MMap only, no?

**Comment by devnexen** [comment]
Yes I had heavy hand however I think it still apply to util_Calloc no ?

**Comment by robertswiecki** [comment]
Reading through https://gcc.gnu.org/onlinedocs/gcc/Common-Function-Attributes.html#Common-Function-Attributes is confusing - it doesn't use the 'undefined' wording, but focuses on pointer aliasing and non-NULL-ness. I think it's fine for all. I'll leave it open for 24h and probably merge in whatever form you'll leave it, b/c I don't fully understand the description. It seems it can be even applied to fopen().

**Comment by devnexen** [comment]
>  It seems it can be even applied to fopen().

yes it does.

**Pull request merged**
