### PR TITLE
add run time: * days * hrs * min * sec

### PR DESCRIPTION
**Pull request by riusksk**
I add run time, modify
> Start time: 2016-05-14 14:48:53 (74169 seconds elapsed)

to
>Start time: 2016-05-15 10:56:28
>Run time: 0 hrs 0 min 15 sec

it also can display the number of days if run time >= 24 hours:
>Run time: 1 days 0 hrs 0 min 15 sec

### CODE REVIEW

**Comment by riusksk** [comment]
I already signed it

**Comment by riusksk** [comment]
the above wifiadmin also is me(riusksk), beacause previous git global config user name was wrong

**Comment by robertswiecki** [comment]
Nice set of changes! Could you please change the following

* sprintf -> snprintf
* The correct format directive for unsigned int is %u

**Comment by riusksk** [comment]
Thanks to remind , I has been modified it.

**Pull request merged**
